### ISSUE TITLE
🐞[Bug]Tasks.vue 버그 리포트

### ISSUE THREAD

**Issue by esueng** [beyond-sw-camp/be08-fin-200OK-CONCENTRIC-frontend#69]
# Environment
> 발생 환경에 대한 상세를 작성해주세요
- OS: 
- IDE:
- Build Tool(version): 
- 사용 언어: 

# Error Message
> ![image](https://github.com/user-attachments/assets/7b428a14-a07a-4cb6-a0d6-7d32fef02afe)
![image](https://github.com/user-attachments/assets/5476caff-ce16-4e4a-80f6-a6f7be8d8634)
( 로그인 되어있는데도 tasks 안불러와짐 )
# Description
> newTasks 자료형이 잘못된 것 같아요

# Steps to Reproduce
> 버그를 재현할 수 있는 방법을 순서대로 작성해주세요
1. 재현방법 모름
2. 
3. 

# Expected Result
> 버그가 발생하지 않았을 때 수행 되어야할 결과에 대해 작성해주세요.
tasks 잘 불러와져야하는데...

# Actual Result
> 버그로 인해 발생한 결과에 대해 작성해주세요.

# ETC (선택 사항)

**Comment by esueng** [comment]
아 로그아웃도 안됩니다.

**Comment by sjpark-08** [comment]
메인 풀받아서 돌려봤는데 잘되네요
